frase = raw_input('Digite uma frase: ')
print('Espacos: ' + str(frase.count(' ')))
print('a :' + str(frase.count('a')))
print('e :' + str(frase.count('e')))
print('i :' + str(frase.count('i')))
print('o :' + str(frase.count('o')))
print('u :' + str(frase.count('u')))